image:
  file: .gitpod.Dockerfile
tasks:
  - command: >
      make --help
vscode:
  extensions:
    - https://open-vsx.org/api/llvm-vs-code-extensions/vscode-clangd/0.1.33/file/llvm-vs-code-extensions.vscode-clangd-0.1.33.vsix
    
